# Generated by Django 5.0.6 on 2025-08-18 03:02

import django.db.models.deletion
import orgs.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OAuthClient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "client_id",
                    models.CharField(
                        default=orgs.models.generate_client_id,
                        max_length=32,
                        unique=True,
                    ),
                ),
                ("client_secret_hash", models.CharField(max_length=128)),
                ("redirect_uris", models.JSONField(default=list)),
                ("post_logout_redirect_uris", models.JSONField(default=list)),
                ("is_confidential", models.BooleanField(default=True)),
                ("pkce_enforced", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="orgs.organization",
                    ),
                ),
            ],
        ),
    ]
